name: Frontend - Deploy (Develop)

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: sa-east-1
      DIST_DIR: dist
      S3_BUCKET: ecommerce-dev-frontend-bucket
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set default.region "$AWS_REGION"
          aws sts get-caller-identity

      # ---- Importa el orden: ASSETS primero, despues index.html ----
      - name: Upload assets (immutable cache)
        run: |
          aws s3 sync "$DIST_DIR/" "s3://$S3_BUCKET/" \
            --exclude "index.html" \
            --cache-control "public,max-age=31536000,immutable" \
            --delete \
            --no-progress

      - name: Upload index.html (no-cache) LAST
        run: |
          aws s3 cp "$DIST_DIR/index.html" "s3://$S3_BUCKET/index.html" \
            --cache-control "no-cache" \
            --content-type "text/html" \
            --no-progress

      - name: Invalidate CloudFront (/, /index.html)
        env:
          CF_DIST_ID: E1APKC36MCV7XY
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "$CF_DIST_ID" \
            --paths "/" "/index.html"
